"""empty message

Revision ID: f41eebfe427a
Revises: 
Create Date: 2019-08-29 14:02:36.344423

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f41eebfe427a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('links_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('url', sa.String(length=256), nullable=True),
    sa.Column('status', sa.Integer(), nullable=True),
    sa.Column('wal', sa.String(length=1), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_links_log_url'), 'links_log', ['url'], unique=False)
    op.create_table('search',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('keyword', sa.String(length=256), nullable=True),
    sa.Column('numLinks', sa.Integer(), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_search_keyword'), 'search', ['keyword'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_search_keyword'), table_name='search')
    op.drop_table('search')
    op.drop_index(op.f('ix_links_log_url'), table_name='links_log')
    op.drop_table('links_log')
    # ### end Alembic commands ###
